
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black

-   repo: https://github.com/timothycrosley/isort
# 4.3.21-2 is broken
# https://github.com/timothycrosley/isort/issues/1154
    rev: 4.3.21
    hooks:
    -   id: isort